#
# Build
#

if {[have_spec odroid_xu]} {
	puts "Run script does not support this platform."
	exit 0
}

set build_components {
	core init
	drivers/timer
        drivers/framebuffer
}

source ${genode_dir}/repos/base/run/platform_drv.inc

append_platform_drv_build_components

build $build_components

create_boot_directory

#
# Generate config
#

append config {
<config>
	<parent-provides>
		<service name="ROM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
	</parent-provides>
	<default-route>
		<!--<any-service> <parent/> <any-child/> </any-service>-->
	</default-route>
	<default caps="100"/>}

#append_platform_drv_config

append config {
	<start name="timer">
            <resource name="RAM" quantum="1M"/>
            <provides>
                <service name="Timer"/>
            </provides>
            <route>
                <service name="PD"><parent/></service>
                <service name="CPU"><parent/></service>
                <service name="LOG"><parent/></service>
                <service name="ROM"><parent/></service>
            </route>
	</start>

        <start name="fb_boot_drv">
            <resource name="RAM" quantum="4M"/>
            <provides>
                <service name="Framebuffer"/>
            </provides>
            <route>
                <service name="PD"><parent/></service>
                <service name="CPU"><parent/></service>
                <service name="LOG"><parent/></service>
                <service name="ROM"><parent/></service>
                <service name="Timer"><child name="timer"/></service>
                <service name="IO_MEM"><parent/></service>
            </route>
        </start>

        <start name="acpi_report_rom">
            <binary name="report_rom"/>
            <resource name="RAM" quantum="2M"/>
            <provides>
                <service name="ROM"/>
                <service name="Report"/>
            </provides>
            <config>
                <policy label="platform_drv -> acpi" report="acpi_drv -> acpi"/>
            </config>
            <route>
                <service name="PD"><parent/></service>
                <service name="CPU"><parent/></service>
                <service name="LOG"><parent/></service>
                <service name="ROM"><parent/></service>
            </route>
        </start>

        <start name="platform_drv" caps="800">
            <resource name="RAM" quantum="4M"/>
            <provides>
                <service name="Platform"/>
            </provides>
            <route>
                <service name="ROM" label="acpi"><child name="acpi_report_rom"/></service>
                <service name="PD"><parent/></service>
                <service name="CPU"><parent/></service>
                <service name="LOG"><parent/></service>
                <service name="ROM"><parent/></service>
            </route>
        </start>
</config>
}

install_config $config

#
# Boot modules
#

# generic modules
set boot_modules {
	core ld.lib.so init
	timer
        fb_boot_drv
}

append_platform_drv_boot_modules

build_boot_image $boot_modules


run_genode_until forever
