#
# \brief  Showcases terminal_log server on Yoga 900
# \author Alexander Senier
# \date   2016-09-17
#

set build_components {
	core init
	drivers/timer drivers/platform
        drivers/ahci
        test/blk/bench
}
lappend_if [have_spec linux] build_components lib/initramfs

source ${genode_dir}/repos/base/run/platform_drv.inc
append_platform_drv_build_components

build $build_components

set mke2fs [check_installed mke2fs]
set dd     [check_installed dd]
exec -ignorestderr $dd if=/dev/zero of=bin/ext2.raw bs=1M count=16
exec -ignorestderr $mke2fs -F bin/ext2.raw

create_boot_directory

append config {
<config>
	<parent-provides>
            <service name="ROM"/>
            <service name="RAM"/>
            <service name="IRQ"/>
            <service name="IO_MEM"/>
            <service name="IO_PORT"/>
            <service name="PD"/>
            <service name="RM"/>
            <service name="CPU"/>
            <service name="LOG"/>
	</parent-provides>
	<default-route/>
        <default caps="250"/>

	<start name="timer">
            <resource name="RAM" quantum="1M"/>
            <provides><service name="Timer"/></provides>
            <route>
                <service name="PD"><parent/></service>
                <service name="CPU"><parent/></service>
                <service name="LOG"><parent/></service>
                <service name="ROM"><parent/></service>
            </route>
	</start>

        <!-- platform driver -->

	<start name="platform_drv"  caps="800">
		<resource name="RAM" quantum="4M" constrain_phys="yes"/>
		<provides>
			<service name="Platform"/>
			<service name="Acpi"/>
		</provides>
		<route>
                        <service name="LOG"><parent/></service>
			<service name="PD">     <parent/> </service>
			<service name="CPU">    <parent/> </service>
                        <service name="ROM">    <parent/> </service>
                        <!-- used by ahci -->
                        <service name="IO_PORT"><parent/></service>
                        <service name="IO_MEM"><parent/></service>
                        <service name="IRQ"><parent/></service>
                        <!--
                        -->
		</route>
		<config acpi="no" verbose="yes">
                        <policy label_prefix="ps2_drv">  <device name="PS2"/> </policy>
			<policy label_prefix="nic_drv">  <pci class="ETHERNET"/> </policy>
			<policy label_prefix="fb_drv">   <pci class="VGA"/> </policy>
                        <policy label_prefix="wifi_drv"> <pci class="WIFI"/> </policy>
                        <policy label_prefix="usb_drv">  <pci class="USB"/> </policy>
                        <policy label_prefix="ahci_drv"> <pci class="AHCI"/> </policy>
			<policy label_prefix="audio_drv"> <pci class="AUDIO"/> <pci class="HDAUDIO"/> </policy>
			<policy label_prefix="intel_fb_drv" irq_mode="nomsi">
				<pci class="VGA"/>
				<pci bus="0" device="0" function="0"/>
				<pci class="ISABRIDGE"/>
                        </policy>
		</config>
	</start>

        <!-- /platform driver -->

        <!-- ahci driver -->

	<start name="ahci_drv">
            <resource name="RAM" quantum="10M" />
            <provides><service name="Block" /></provides>
            <config>
                <policy label_prefix="test-ahci" device="0" writeable="no" />
            </config>
            <route>
                <service name="PD"><parent/></service>
                <service name="CPU"><parent/></service>
                <service name="LOG"><parent/></service>
                <service name="ROM"><parent/></service>
                <service name="Platform"><child name="platform_drv"/></service>
                <service name="Timer"><child name="timer"/></service>
                <service name="IO_MEM"><parent/></service>
            </route>
	</start>

	<start name="test-ahci">
            <binary name="test-blk-bench" />
            <resource name="RAM" quantum="5M" />
            <route>
                <service name="PD"><parent/></service>
                <service name="CPU"><parent/></service>
                <service name="LOG"><parent/></service>
                <service name="ROM"><parent/></service>
                <service name="Block"><child name="ahci_drv"/></service>
                <service name="Timer"><child name="timer"/></service>
            </route>
        </start>

        <!-- /ahci driver -->
</config>
}

install_config $config

# generic modules
set boot_modules {
	core init ld.lib.so
	timer
        ahci_drv platform_drv
        test-blk-bench
}
lappend_if [have_spec linux] boot_modules initramfs

build_boot_image $boot_modules

append qemu_args " -m 512 "
append qemu_args " -drive id=disk,file=bin/ext2.raw,format=raw,if=none -device ahci,id=ahci -device ide-hd,drive=disk,bus=ahci.0 -boot d"
append qemu_args " -drive id=cd,file=[run_dir]/../ahci_test_log.iso,if=none,media=cdrom -device ide-cd,drive=cd,bus=ahci.1"

run_genode_until forever
