
#
# \brief  Showcases terminal_log server on Yoga 900
# \author Alexander Senier
# \date   2016-09-17
#

set build_components {
    core init
    test/empty
}

lappend_if [have_spec linux] build_components lib/initramfs

source ${genode_dir}/repos/base/run/platform_drv.inc

build $build_components

create_boot_directory

append config {
<config>
	<parent-provides>
            <service name="ROM"/>
            <service name="RAM"/>
            <service name="IRQ"/>
            <service name="IO_MEM"/>
            <service name="IO_PORT"/>
            <service name="PD"/>
            <service name="RM"/>
            <service name="CPU"/>
            <service name="LOG"/>
	</parent-provides>
	<default-route/>
        <default caps="250"/>

        <start name="test-empty">
            <resource name="RAM" quantum="1M"/>
            <route>
                <service name="PD"><parent/></service>
                <service name="ROM"><parent/></service>
                <service name="LOG"><parent/></service>
                <service name="CPU"><parent/></service>
            </route>
        </start>

</config>
}

install_config $config

# generic modules
set boot_modules {
    core init ld.lib.so
    test-empty
}

lappend_if [have_spec linux] boot_modules initramfs

# since platform_info is not provided by the kernel we have to provide it manually.
# the simplest solution would be putting a file containing <platform_info/> to bin/platform_info

build_boot_image $boot_modules

append qemu_args " -m 512 "

run_genode_until forever
