#
# \brief  Showcases terminal_log server on Yoga 900
# \author Alexander Senier
# \date   2016-09-17
#

set build_components {
	core init
	drivers/framebuffer drivers/input drivers/timer
	server/nitpicker server/nit_fb
        server/terminal server/terminal_log test/nitpicker app/pointer
        test/log
        lib/initramfs
        test/framebuffer
}

source ${genode_dir}/repos/base/run/platform_drv.inc
append_platform_drv_build_components

build $build_components

create_boot_directory

append config {
<config>
	<parent-provides>
            <service name="ROM"/>
            <service name="RAM"/>
            <service name="IRQ"/>
            <service name="IO_MEM"/>
            <service name="IO_PORT"/>
            <service name="PD"/>
            <service name="RM"/>
            <service name="CPU"/>
            <service name="LOG"/>
	</parent-provides>
	<default-route/>
        <default caps="250"/>

        <!-- log core -->

	<start name="timer">
            <resource name="RAM" quantum="1M"/>
            <provides><service name="Timer"/></provides>
            <route>
                <service name="PD"><parent/></service>
                <service name="CPU"><parent/></service>
                <service name="LOG"><parent/></service>
                <service name="ROM"><parent/></service>
            </route>
	</start>
        
        <!-- platform driver -->
        
	<start name="platform_drv"  caps="800">
		<resource name="RAM" quantum="4M" constrain_phys="yes"/>
		<provides>
			<service name="Platform"/>
		</provides>
		<route>
			<service name="ROM" label="system"> <child name="acpi_report_rom"/> </service>
			<service name="ROM" label="acpi"> <child name="acpi_report_rom"/> </service>
                        <!--<service name="LOG"><child name="terminal_log"/></service>-->
                        <service name="LOG"><parent/></service>
			<service name="PD">     <parent/> </service>
			<service name="CPU">    <parent/> </service>
                        <service name="ROM">    <parent/> </service>
                        <!-- used by fb -->
                        <service name="IO_PORT"><parent/></service>
                        <!--
                        <service name="IO_MEM"><parent/></service>
                        <service name="IRQ"><parent/></service>
                        -->
		</route>
		<config acpi="no" verbose="yes">
                        <policy label_prefix="ps2_drv">  <device name="PS2"/> </policy>
			<policy label_prefix="nic_drv">  <pci class="ETHERNET"/> </policy>
			<policy label_prefix="fb_drv">   <pci class="VGA"/> </policy>
                        <policy label_prefix="wifi_drv"> <pci class="WIFI"/> </policy>
                        <policy label_prefix="usb_drv">  <pci class="USB"/> </policy>
                        <policy label_prefix="ahci_drv"> <pci class="AHCI"/> </policy>
			<policy label_prefix="audio_drv"> <pci class="AUDIO"/> <pci class="HDAUDIO"/> </policy>
			<policy label_prefix="intel_fb_drv" irq_mode="nomsi">
				<pci class="VGA"/>
				<pci bus="0" device="0" function="0"/>
				<pci class="ISABRIDGE"/>
                        </policy>
		</config>
	</start>

        <!-- /platform driver -->

        <!-- framebuffer driver -->

        <start name="fb_drv">
            <resource name="RAM" quantum="4M"/>
            <provides>
                <service name="Framebuffer"/>
            </provides>
            <route>
                <service name="PD"><parent/></service>
                <service name="CPU"><parent/></service>
                <service name="LOG"><parent/></service>
                <service name="ROM"><parent/></service>
                <service name="Platform"><child name="platform_drv"/></service>
                <service name="IO_PORT"><parent/></service>
                <service name="IO_MEM"><parent/></service>
                <service name="Timer"><child name="timer"/></service>
            </route>
        </start>


	<start name="test-framebuffer">
		<resource name="RAM" quantum="10M"/>
            <route>
                <service name="PD"><parent/></service>
                <service name="CPU"><parent/></service>
                <service name="LOG"><parent/></service>
                <service name="ROM"><parent/></service>
                <service name="Timer"><child name="timer"/></service>
                <service name="Framebuffer"><child name="fb_drv"/></service>
            </route>
	</start>

</config>
}

install_config $config

# generic modules
set boot_modules {
	core init ld.lib.so
	timer 
        fb_drv
        initramfs
        platform_drv
	test-framebuffer
}

append_platform_drv_boot_modules

build_boot_image $boot_modules

append qemu_args " -m 512 "

run_genode_until forever
