#
# \brief  Showcases terminal_log server on Yoga 900
# \author Alexander Senier
# \date   2016-09-17
#

set use_qemu [have_include "power_on/qemu"]

set build_components {
	core init
	drivers/framebuffer drivers/input drivers/timer
	server/nitpicker server/nit_fb
	server/terminal server/terminal_log test/nitpicker app/pointer
        drivers/usb drivers/usb_block server/report_rom
}

source ${genode_dir}/repos/base/run/platform_drv.inc

#override default platform policies
#proc platform_drv_policy {} {
#    return {
#    <!--<policy label="usb_drv">
#            <pci class="USB"/>
#        </policy>-->
#    }
#}


append_platform_drv_build_components

build $build_components

create_boot_directory

append config {
<config verbose="yes">
	<parent-provides>
            <service name="ROM"/>
            <service name="RAM"/>
            <service name="IRQ"/>
            <service name="IO_MEM"/>
            <service name="IO_PORT"/>
            <service name="PD"/>
            <service name="RM"/>
            <service name="CPU"/>
            <service name="LOG"/>
	</parent-provides>
	<default-route/>
        <default caps="250"/>

        <!-- log core -->

	<start name="timer">
            <resource name="RAM" quantum="1M"/>
            <provides><service name="Timer"/></provides>
            <route>
                <service name="PD"><parent/></service>
                <service name="CPU"><parent/></service>
                <service name="LOG"><parent/></service>
                <service name="ROM"><parent/></service>
            </route>
	</start>
	
        <start name="dummy_input_drv">
            <resource name="RAM" quantum="1M"/>
            <provides><service name="Input"/></provides>
            <route>
                <service name="PD"><parent/></service>
                <service name="CPU"><parent/></service>
                <service name="LOG"><parent/></service>
                <service name="ROM"><parent/></service>
            </route>
	</start>
	<alias name="input_drv" child="dummy_input_drv"/>

        <start name="fb_boot_drv">
            <resource name="RAM" quantum="16M"/>
            <provides>
                <service name="Framebuffer"/>
            </provides>
            <route>
                <service name="PD"><parent/></service>
                <service name="CPU"><parent/></service>
                <service name="LOG"><parent/></service>
                <service name="ROM"><parent/></service>
		<service name="Timer">     <child name="timer"/> </service>
                <service name="IO_MEM"><parent/></service>
            </route>
        </start>
	<start name="nitpicker">
            <resource name="RAM" quantum="1M"/>
            <provides><service name="Nitpicker"/></provides>
            <config>
                <domain name="pointer" layer="1" content="client" label="no" origin="pointer" />
                <domain name="default" layer="2" content="client" label="no" focus="click" hover="always" />
                <policy label="pointer" domain="pointer"/>
                <default-policy domain="default"/>
            </config>
            <route>
                <service name="Input">       <child name="input_drv"/> </service>
                <service name="Framebuffer"> <child name="fb_boot_drv"/>    </service>
                <service name="PD"><parent/></service>
                <service name="CPU"><parent/></service>
                <service name="LOG"><parent/></service>
                <service name="ROM"><parent/></service>
                <service name="Timer">     <child name="timer"/> </service>
            </route>
	</start>

	<start name="pointer">
            <resource name="RAM" quantum="1M"/>
            <route>
                <service name="PD"><parent/></service>
                <service name="CPU"><parent/></service>
                <service name="LOG"><parent/></service>
                <service name="ROM"><parent/></service>
		<service name="Nitpicker"> <child name="nitpicker"/> </service>
            </route>
	</start>

	<start name="terminal_fb">
            <binary name="nit_fb"/>
            <resource name="RAM" quantum="16M"/>
            <provides>
                    <service name="Framebuffer"/>
                    <service name="Input"/>
            </provides>
            <config xpos="0" ypos="0" width="1280" height="720" refresh_rate="25"/>
            <route>
                <service name="PD"><parent/></service>
                <service name="CPU"><parent/></service>
                <service name="LOG"><parent/></service>
                <service name="ROM"><parent/></service>
		<service name="Nitpicker"> <child name="nitpicker"/> </service>
            </route>
	</start>

	<start name="terminal">
            <resource name="RAM" quantum="3M"/>
            <provides><service name="Terminal"/></provides>
            <config>
                <!-- supported built-in font sizes are 8, 12, 16, 24 and 36 -->
                <font size="8" />
            </config>
            <route>
                <service name="Input">       <child name="terminal_fb"/> </service>
                <service name="Framebuffer"> <child name="terminal_fb"/> </service>
                <service name="PD"><parent/></service>
                <service name="CPU"><parent/></service>
                <service name="LOG"><parent/></service>
                <service name="ROM"><parent/></service>
                <service name="Timer">     <child name="timer"/> </service>
            </route>
	</start>

	<start name="terminal_log">
            <resource name="RAM" quantum="1M"/>
            <provides><service name="LOG"/></provides>
            <route>
                <service name="PD"><parent/></service>
                <service name="CPU"><parent/></service>
                <service name="LOG"><parent/></service>
                <service name="ROM"><parent/></service>
		<service name="Terminal">  <child name="terminal"/> </service>
            </route>
        </start>

        <!-- /log core -->

        <!-- platform driver -->
<!-- 
        <start name="acpi_report_rom">
            <binary name="report_rom"/>
            <resource name="RAM" quantum="2M"/>
            <provides>
                <service name="ROM"/>
                <service name="Report"/>
            </provides>
            <config>
                <policy label="platform_drv -> acpi" report="acpi_drv -> acpi"/>
            </config>
            <route>
                <service name="PD"><parent/></service>
                <service name="CPU"><parent/></service>
                <service name="LOG"><parent/></service>
                <service name="ROM"><parent/></service>
            </route>
        </start>

        <start name="platform_drv" caps="800">
            <resource name="RAM" quantum="4M"/>
            <provides>
                <service name="Platform"/>
            </provides>
            <route>
                <service name="ROM" label="acpi"><child name="acpi_report_rom"/></service>
                <service name="ROM" label="system"><child name="acpi_report_rom"/></service>
                <service name="PD"><parent/></service>
                <service name="CPU"><parent/></service>
                <service name="LOG"><parent/></service>
                <service name="ROM"><parent/></service>
            </route>
        </start>
-->
        <!-- /platform driver -->
        }
#        append_platform_drv_config
        append config {
	<start name="acpi_drv"  caps="400" >
		<resource name="RAM" quantum="3M"/>
		<route>
			<service name="IO_MEM"> <parent/> </service>
			<service name="LOG">    <parent/> </service>
			<service name="PD">     <parent/> </service>
			<service name="RM">     <parent/> </service>
			<service name="CPU">    <parent/> </service>
			<service name="ROM">    <parent/> </service>
			<service name="Report"> <child name="acpi_report_rom"/> </service>
			<service name="ROM" label="platform_info"> <parent/> </service>
		</route>
	</start>
	<start name="acpi_report_rom" >
		<binary name="report_rom"/>
		<resource name="RAM" quantum="2M"/>
		<provides>
			<service name="ROM" />
			<service name="Report" />
		</provides>
		<config>
			<policy label="platform_drv -> acpi" report="acpi_drv -> acpi"/>
		</config>
		<route>
			<service name="LOG"> <parent/> </service>
			<service name="PD">     <parent/> </service>
			<service name="CPU">    <parent/> </service>
			<service name="ROM">    <parent/> </service>
		</route>
	</start>
	<start name="platform_drv"  caps="800">
		<resource name="RAM" quantum="4M" constrain_phys="yes"/>
		<provides>
			<service name="Platform"/>
			<service name="Acpi"/>
		</provides>
		<route>
			<service name="ROM" label="system"> <child name="acpi_report_rom"/> </service>
			<service name="ROM" label="acpi"> <child name="acpi_report_rom"/> </service>
			<service name="LOG"> <parent/> </service>
			<service name="PD">     <parent/> </service>
			<service name="CPU">    <parent/> </service>
                        <service name="ROM">    <parent/> </service>
                        <!-- used by usb -->
                        <service name="IO_PORT"><parent/></service>
                        <service name="IO_MEM"><parent/></service>
                        <service name="IRQ"><parent/></service>
		</route>
		<config>
                        <policy label_prefix="ps2_drv">  <device name="PS2"/> </policy>
			<policy label_prefix="nic_drv">  <pci class="ETHERNET"/> </policy>
			<policy label_prefix="fb_drv">   <pci class="VGA"/> </policy>
                        <policy label_prefix="wifi_drv"> <pci class="WIFI"/> </policy>
                        <policy label_prefix="usb_drv">  <pci class="USB"/> </policy>
                        <policy label_prefix="ahci_drv"> <pci class="AHCI"/> </policy>
			<policy label_prefix="audio_drv"> <pci class="AUDIO"/> <pci class="HDAUDIO"/> </policy>
			<policy label_prefix="intel_fb_drv" irq_mode="nomsi">
				<pci class="VGA"/>
				<pci bus="0" device="0" function="0"/>
				<pci class="ISABRIDGE"/>
                        </policy>
		</config>
	</start>

    <!-- usb driver -->
        
        <start name="usb_drv" caps="120">
            <resource name="RAM" quantum="16M"/>
            <provides>
                <service name="Usb"/>
            </provides>
            <config ehci="yes" uhci="yes" xhci="yes">
            </config>
            <route>
                <service name="PD"><parent/></service>
                <service name="CPU"><parent/></service>
                <service name="LOG"><child name="terminal_log"/></service>
                <service name="ROM"><parent/></service>
                <service name="Platform"><child name="platform_drv"/></service>
                <service name="RM"><parent/></service>
                <service name="Timer"><child name="timer"/></service>
            </route>
        </start>

        <!-- /usb driver -->

</config>
}

install_config $config

# generic modules
set boot_modules {
	core init ld.lib.so
	timer nitpicker pointer testnit nit_fb 
        terminal terminal_log
        fb_boot_drv dummy_input_drv
        usb_drv usb_block_drv report_rom
}

append_platform_drv_boot_modules

build_boot_image $boot_modules

set disk_image "bin/test.img"
set cmd "dd if=/dev/zero of=$disk_image bs=1M count=16"
if {$use_qemu} {
	puts "creating disk image:\n$cmd"
	catch { exec sh -c $cmd }
}

append qemu_args " -m 512 "
append qemu_args " -M pc -boot order=d "
append qemu_args " -drive if=none,id=disk,file=$disk_image,format=raw "
append qemu_args " -device usb-ehci,id=ehci -device usb-storage,bus=ehci.0,drive=disk "
run_genode_until forever
